### PR TITLE
Add Semesters and Advisors

### PR DESCRIPTION
**Pull request by grace-hopp**
Add semesters and advisors routes, models, and controllers files.

### CODE REVIEW

**Comment by ChloeSheasby** [comment]
This looks good! I think we just have to add the file path to the server.js file.

**Review by JoshKeenMurr — APPROVED** [review]
Checked on postman and get requests works

**Comment by JoshKeenMurr** [comment]
Updated the advisors and semesters so that CRUD works with them. Have this weird check thing now but North says its not a problem. @ChloeSheasby @Joshua-Stewart1 @grace-hopp  LMK what y'all think.

**Review by ChloeSheasby — CHANGES_REQUESTED** [review]
This looks good but since the id auto-increments, you don't need advisorID or semesterID.

**Review by JoshKeenMurr — APPROVED** [review]

**Pull request merged**
